# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Lookup calibration prep (seed.sh Step 6z, after the atlas pipeline).

Run via:
    docker exec -i <service> python manage.py shell < scripts/seed-lookup.py

Loads `fixtures/lookup/{pim_products,atlas_products}.json` (generated by
`scripts/generate-lookup-fixtures.py` — see that file for the pair-class design), attaches each
product's picture from the in-network `fixtures` host, runs `lookup_backfill` (text; always) and
`lookup_backfill --images` (only when the `embed` container answers — a dead backend would otherwise
spend the whole run on HTTP timeouts), then seeds one pending `duplicate_in_pim` enrichment proposal
so the `@lookup-oneshot` accept scenario has something to accept.

Idempotent: wipes prior LKP-PIM-*/atl-lookup-* rows before recreating (same convention as
`seed-atlas-e2e.py`); the enrichment proposal intake supersedes its own prior pending row.
Target channel: `default-europe` (package Step 4 must have run — this step lives after Step 6x).
Feature set: `furniture` (loaded by fixtures/django_pim.cfg.yaml, Step 2).
"""

import json
from contextlib import suppress
from decimal import Decimal
from pathlib import Path

import requests
from django.core.management import call_command

FIXTURES_HOST = "http://fixtures:8000"
IMG_URL = f"{FIXTURES_HOST}/fixtures/lookup/img"
FIXTURES_DIR = Path("/entirius/test-package/fixtures/lookup")

CHANNEL = "default-europe"
FEATURE_SET = "furniture"
SOURCE_IDXS = ["atl-lookup-a", "atl-lookup-b"]
SKU_PREFIX = "LKP-PIM-"
# Reserved exact_dup indices (both documented here so seed-lookup.py and the .feature file agree —
# a BDD step comment cannot import a Python constant, so it names the constant instead):
#   index 1 -> PROPOSAL_PAIR_INDEX: the pending duplicate_in_pim proposal the @lookup-oneshot accept
#              scenario consumes.
#   index 2 -> CREATE_HOOK_PAIR_INDEX: the "Creating a PIM product with a duplicate EAN..." scenario
#              reuses this pair's atlas EAN on a brand-new PIM product (features/lookup/lookup_check.feature).
PROPOSAL_PAIR_INDEX = 1
CREATE_HOOK_PAIR_INDEX = 2
EMBED_TIMEOUT_S = 2


def _load(name: str) -> list[dict]:
    return json.loads((FIXTURES_DIR / name).read_text(encoding="utf-8"))


def _wipe_prior_run() -> None:
    from django_pim.models import Product, RealProduct

    Product.objects.filter(real_product__sku__startswith=SKU_PREFIX).delete()
    RealProduct.objects.filter(sku__startswith=SKU_PREFIX).delete()
    with suppress(Exception):
        from django_atlas.models import Source, SourceProduct

        sources = list(Source.objects.filter(idx__in=SOURCE_IDXS))
        if sources:
            SourceProduct.objects.filter(source__in=sources).delete()


def _brand_attribute_idx(brand: str) -> str:
    return brand.strip().lower().replace(" ", "-")


def _ensure_brand_attributes(pim_products: list[dict]) -> str:
    from django_pim.models import Attribute, Feature

    brand_feature = Feature.objects.get(idx="brand")
    brands = sorted({p["brand"] for p in pim_products})
    for brand in brands:
        Attribute.objects.get_or_create(
            feature=brand_feature, idx=_brand_attribute_idx(brand), defaults={"name_t9n": {"en": brand}}
        )
    return f"brand attributes: {len(brands)} ready"


def _attach_main_picture(product, image_filename: str) -> None:
    """The real picture path (PictureDownloadUrl cache / Picture / ProductPicture MAIN).

    `HashedImageFieldFile` needs a real file handle — `python-magic`'s `from_file()` requires a
    filesystem path, an in-memory `ContentFile` will not do (see `product_picture_service.upload_picture`,
    the same pattern the admin picture-upload endpoint uses).
    """
    import os
    import tempfile

    from django.core.files import File
    from django_pim.managers.picture import PictureManager
    from django_pim.models import Picture, PictureRoleEnum, ProductPicture

    url = f"{IMG_URL}/{image_filename}"
    picture = PictureManager.get_picture_from_url_cache(url)
    if picture is None:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        with tempfile.NamedTemporaryFile(suffix=f"_{image_filename}", delete=False) as tmp:
            tmp.write(response.content)
            tmp_path = tmp.name
        try:
            picture = Picture(original_file_name=image_filename)
            with open(tmp_path, "rb") as handle:
                picture.image.save(image_filename, File(handle))
            picture.save()
        finally:
            os.unlink(tmp_path)
        PictureManager.set_picture_from_url(picture, url)
    ProductPicture.objects.update_or_create(
        product=product, picture_role=PictureRoleEnum.MAIN, language=None, defaults={"picture": picture, "position": 0}
    )


def _create_pim_products(pim_products: list[dict]) -> str:
    from django_pim.services.product_service import create_product

    for entry in pim_products:
        attributes = [
            {"feature_idx": "name", "value_txt_t9n": {"en": entry["name"]}},
            {"feature_idx": "brand", "attribute_idx": _brand_attribute_idx(entry["brand"])},
        ]
        if entry.get("mpn"):
            attributes.append({"feature_idx": "mpn", "value_txt": entry["mpn"]})
        product = create_product(
            channel_idx=CHANNEL,
            sku=entry["sku"],
            feature_set_idx=FEATURE_SET,
            ean=entry["ean"] or None,
            weight=str(entry["weight_kg"]),
            attributes=attributes,
        )
        _attach_main_picture(product, entry["image"])
    return f"pim products: {len(pim_products)} created with MAIN pictures"


def _common_source_defaults() -> dict:
    from django_atlas.enums import ReviewMode, SourceKind, SourceType
    from django_regional.models import Currency, Language

    return {
        "kind": SourceKind.PROCUREMENT,
        "source_type": SourceType.FEED,
        "review_mode": ReviewMode.MANUAL,
        "is_active": True,
        "is_trusted": True,
        "default_language": Language.objects.get(iso2="en"),
        "default_currency": Currency.objects.get(iso3="EUR"),
        "qty_subtract": 0,
        "qty_minimum": 0,
        "realproduct_match_tolerance_pct": 10,
        "disable_ean_auto_link": False,
    }


def _ensure_atlas_sources() -> dict:
    from django_atlas.models import Source

    # Source.sku_prefix is max_length=10 — SOURCE_IDXS (~14 chars) does not fit.
    names_and_prefixes = [("Lookup Calibration Feed A", "LKPA"), ("Lookup Calibration Feed B", "LKPB")]
    sources = {}
    for idx, (name, prefix) in zip(SOURCE_IDXS, names_and_prefixes, strict=True):
        source, _ = Source.objects.update_or_create(
            idx=idx, defaults={**_common_source_defaults(), "name": name, "sku_prefix": prefix}
        )
        sources[idx] = source
    return sources


def _create_atlas_products(atlas_products: list[dict], sources: dict) -> str:
    from django_atlas.enums import ProductStatus
    from django_atlas.models import SourceProduct

    for entry in atlas_products:
        data = {"brand": entry["brand"], "weight": entry["weight_kg"]}
        if entry.get("mpn"):
            data["mpn"] = entry["mpn"]
        SourceProduct.objects.update_or_create(
            source=sources[entry["source_idx"]],
            external_id=entry["external_id"],
            defaults={
                "feed": None,
                "name": entry["name"],
                "cost": Decimal("10.0000"),
                "currency": "EUR",
                "stock": 5,
                "ean": entry["ean"],
                "image_urls": [f"{IMG_URL}/{entry['image']}"],
                "data": data,
                "status": ProductStatus.NEW,
                "pushed_to_channel_idxs": [],
                "pushed_by": None,
                "pushed_at": None,
                "real_product": None,
                "reviewed_by": None,
                "reviewed_at": None,
            },
        )
    return f"atlas source products: {len(atlas_products)} created across {len(sources)} sources"


def _embed_reachable() -> bool:
    from django_lookup.settings import get_embedding

    config = get_embedding()
    if config.get("provider") != "http" or not config.get("url"):
        return False
    try:
        requests.get(config["url"], timeout=EMBED_TIMEOUT_S)
    except requests.RequestException:
        return False
    return True


def _run_backfill() -> str:
    call_command("lookup_backfill")
    if _embed_reachable():
        call_command("lookup_backfill", "--images")
        return "lookup_backfill: text + images (embed reachable)"
    return "lookup_backfill: text only (embed unreachable — skipped --images, kept the run under 2 min)"


def _ensure_spawn_rule() -> None:
    """`atlas-duplicate-in-pim`, same fields as `django_atlas`'s bundled fixture (etap-13).

    Built via the ORM rather than `loaddata enrichment_spawn_rule_duplicate_in_pim`: that fixture's
    JSON carries no `modified_at`, which trips `SpawnRule`'s NOT NULL column on raw-fixture load —
    an upstream `entirius-django-atlas` bug, out of this repo's reach. The ORM path populates it via
    `BaseModel`'s own `auto_now`, so the row ends up identical either way.
    """
    from django_enrichment.models import SpawnRule

    SpawnRule.objects.update_or_create(
        key="atlas-duplicate-in-pim",
        defaults={
            "module": "atlas",
            "check_key": "duplicate_in_pim",
            "params": {},
            "scope": {},
            "task_type": "lookup_link",
            "task_params": {},
            "limit": 200,
            "cooldown_days": 1,
            "auto": False,
            "active": True,
        },
    )


def _seed_duplicate_proposal() -> str:
    """One pending `duplicate_in_pim` proposal, ready for the @lookup-oneshot accept scenario.

    `django_enrichment`/`django_atlas` are optional — this degrades to a no-op the same way the
    module's own adapter tests do (soft dependency, notes §Provider protocol).
    """
    try:
        from django.apps import apps

        if not (apps.is_installed("django_enrichment") and apps.is_installed("django_atlas")):
            return "duplicate-in-pim proposal: skipped (django_enrichment or django_atlas not installed)"
        _ensure_spawn_rule()
        return _intake_duplicate_proposal()
    except Exception as exc:  # advisory step — never fail the seed over a proposal
        return f"duplicate-in-pim proposal: skipped ({exc})"


def _intake_duplicate_proposal() -> str:
    from dataclasses import asdict
    from decimal import Decimal as Dec

    from django_atlas.models import SourceProduct
    from django_enrichment.services import proposal_service
    from django_lookup.schemas.requests.lookup import LookupQuery
    from django_lookup.services import lookup_service

    i = PROPOSAL_PAIR_INDEX
    source_idx, external_id = "atl-lookup-a" if i % 2 == 0 else "atl-lookup-b", f"EXACT-{i:02d}"
    subject_ref = f"{source_idx}:{external_id}"
    sp = SourceProduct.objects.filter(source__idx=source_idx, external_id=external_id).first()
    if sp is None:
        return "duplicate-in-pim proposal: skipped (seed pair not found)"
    query = LookupQuery(ean=sp.ean or None, name=sp.name, scope=["pim_product"], limit=5)
    result = lookup_service.check(query)
    hit = next((h for h in result.candidates if h.decision in ("match", "review")), None)
    if hit is None:
        return "duplicate-in-pim proposal: skipped (no PIM candidate scored match/review)"
    proposal_service.intake(
        target_module="atlas",
        subject_ref=subject_ref,
        target_kind="link_to_realproduct",
        target_locator={"source_idx": source_idx, "external_id": external_id},
        proposed_value={
            "real_product_sku": hit.ref,
            "score": hit.score,
            "decision": hit.decision,
            "reasons": [asdict(reason) for reason in hit.reasons],
        },
        target_type="source_product",
        subject_label=sp.name,
        source="lookup_seed",
        confidence=Dec(str(round(hit.score / 100, 3))),
    )
    return f"duplicate-in-pim proposal: pending for {subject_ref} -> {hit.ref}"


def main() -> None:
    pim_products = _load("pim_products.json")
    atlas_products = _load("atlas_products.json")
    _wipe_prior_run()
    msgs = [
        _ensure_brand_attributes(pim_products),
        _create_pim_products(pim_products),
    ]
    sources = _ensure_atlas_sources()
    msgs.append(_create_atlas_products(atlas_products, sources))
    msgs.append(_run_backfill())
    msgs.append(_seed_duplicate_proposal())
    print("=== seed-lookup ===")
    for msg in msgs:
        print(msg)
    print("=== done ===")


main()
