@access @admin @v2
Feature: Access staff accounts — an Administrator creates staff accounts from the admin API
  As an access administrator
  I want to create a staff account with its role in one request
  So that a new colleague signs in to the CMS without a superuser (D1)

  Created accounts stay — the API has no delete — so every username is run-unique. A password is generated by a step
  or by the API, kept in the scenario only and never written in a feature file. Each scenario signs in once.

  Background:
    Given a run-unique suffix is saved as "saved.run"

  Scenario: SA-01 accessadmin creates a Viewer with a given password, which signs in through the CMS login
    Given a generated password is saved as "saved.password"
    And I save the newest audit entry id as "saved.mark"
    And the caller is accessadmin
    When the caller sends POST to "api/access/v2/admin/staff/" with body
      """
      {"username": "bdd-staff-{saved.run}", "email": "bdd-staff-{saved.run}@example.com", "role": "viewer", "password": "{saved.password}"}
      """
    Then the answer is 201 with "-"
    And the response field "password" should be null
    And I save the response field "id" as "saved.staff"
    And I save the answer field "grants.0.id" as "saved.grant"
    And the audit log has a "staff.create" entry after "saved.mark" for target "{saved.staff}"
    And the audit log has a "grant.create" entry after "saved.mark" for target "{saved.grant}"
    Given the caller signs in as "bdd-staff-{saved.run}" through customer tokens with the password "saved.password"
    When the caller sends GET to "api/access/v2/me/"
    Then the answer is 200 with "-"
    And the answer field "roles.0.key" is "viewer"

  Scenario: SA-02 without a password the API generates one, answers it once and it signs in
    Given the caller is accessadmin
    When the caller sends POST to "api/access/v2/admin/staff/" with body
      """
      {"username": "bdd-staff-{saved.run}", "email": "bdd-staff-{saved.run}@example.com", "role": "viewer"}
      """
    Then the answer is 201 with "-"
    And the answer was a one-time secret marked no-store
    And I save the answered password as "saved.password"
    Given the caller signs in as "bdd-staff-{saved.run}" through customer tokens with the password "saved.password"
    When the caller sends GET to "api/access/v2/me/"
    Then the answer is 200 with "-"
    And the answer field "roles.0.key" is "viewer"

  Scenario Outline: SA-03 a refused create makes no account — <attempt>
    Given the caller is accessadmin
    When the caller sends POST to "api/access/v2/admin/staff/" with JSON <body>
    Then the answer is <status> with "-"
    And the answer names the field "<field>"
    And no staff account has the username "bdd-staff-{saved.run}"
    And no staff account has the email "bdd-staff-{saved.run}@example.com"

    Examples: refused bodies (the seeded viewer holds "viewer" / viewer@entirius.com)
      | attempt                          | body                                                                                                          | status | field        |
      | duplicate username               | {"username": "viewer", "email": "bdd-staff-{saved.run}@example.com", "role": "viewer"}                        | 409    | -            |
      | duplicate e-mail in another case | {"username": "bdd-staff-{saved.run}", "email": "VIEWER@ENTIRIUS.COM", "role": "viewer"}                       | 409    | -            |
      | weak password                    | {"username": "bdd-staff-{saved.run}", "email": "bdd-staff-{saved.run}@example.com", "role": "viewer", "password": "123"} | 400    | password     |
      | unknown role                     | {"username": "bdd-staff-{saved.run}", "email": "bdd-staff-{saved.run}@example.com", "role": "bdd-no-such-role"} | 400    | role         |
      | is_superuser in the body         | {"username": "bdd-staff-{saved.run}", "email": "bdd-staff-{saved.run}@example.com", "role": "viewer", "is_superuser": true} | 400    | is_superuser |

  Scenario Outline: SA-04 <caller> cannot create a staff account
    Given the caller is <caller>
    When the caller sends POST to "api/access/v2/admin/staff/" with JSON {"username": "bdd-staff-{saved.run}", "email": "bdd-staff-{saved.run}@example.com", "role": "viewer"}
    Then the answer is 403 with "<issue>"
    And the refusal names "<needs>"
    And no staff account has the username "bdd-staff-{saved.run}"

    Examples: below Administrator
      | caller   | issue         | needs                       |
      | manager  | ACCESS_DENIED | needs access.manage:write   |
      | editor   | ACCESS_DENIED | needs access.manage:write   |
      | viewer   | ACCESS_DENIED | needs access.manage:write   |
      | customer | STAFF_ONLY    | A staff account is required |
